version: 0.2

phases:
  pre_build:
    commands:
      # Add ECR_URI and REPOSITORY_NAME on Codebuild enviroment variables
      - PACKAGE_VERSION=$(node -pe "require('./package.json').version")
      - REPOSITORY_URI=$ECR_URI/$REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Build started on `date`  
      - echo Building the docker image
      - docker build -t $REPOSITORY_NAME .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker images...
      - docker push $REPOSITORY_URI:$PACKAGE_VERSION
      - echo Writing image definitions file
      - printf '[{name:"%s","imageUri":"%s"}]' $REPOSITORY_NAME $REPOSITORY_URI:PACKAGE_VERSION > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json