version: 0.2

phases:
  pre_build:
    commands:
      # Add ECR_URI, REPOSITORY_NAME, TAG_NAME and AWS_REGION on Codebuild enviroment variables
      - REPOSITORY_URI=$ECR_URI/$REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Build started on `date`  
      - echo Building the docker image
      - docker build -t $REPOSITORY_NAME .
      - docker tag $REPOSITORY_NAME:"$TAG_NAME" $REPOSITORY_URI
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker images...
      - docker push $REPOSITORY_URI:"$TAG_NAME"
      - echo Writing image definitions file
      - printf '[{name:"%s","imageUri":"%s"}]' $REPOSITORY_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json