
  
version: 0.2

phases:
  pre_build:
    commands:
      # Add ECR_URI, REPOSITORY_NAME, TAG_NAME on Codebuild enviroment variabes
      - REPOSITORY_URI=$ECR_URI/$REPOSITORY_NAME
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Build started on `date`  
      - echo Building the docker image
      - docker build -t $REPOSITORY_NAME:$TAG_NAME .
      - docker tag $REPOSITORY_NAME:$TAG_NAME $REPOSITORY_URI:$TAG_NAME
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker images...
      - docker push $REPOSITORY_URI:$TAG_NAME
      - echo Writing image definitions file
      - printf '[{name:"%s","imageUri":"%s"}]' $REPOSITORY_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json