apiVersion: v1
kind: Service
metadata:
  name: hello-world-express-service
spec:
  selector:
    app: express-app
  ports:
    - protocol: 'TCP'
      port: 9998
      targetPort: 9998
  type: LoadBalancer