apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express
          image: joalisonpereira/hello-world-express